import { Injectable } from '@nestjs/common';
import PDFDocument = require('pdfkit');
import { AnalysesService } from '../analyses/analyses.service';

type ReportAnalysis = Awaited<ReturnType<AnalysesService['findById']>>;

@Injectable()
export class ReportsService {
  constructor(private readonly analyses: AnalysesService) {}

  async markdown(analysisId: string): Promise<string> {
    const analysis = await this.analyses.findById(analysisId);
    const score = analysis.score ?? 0;
    const lines = [
      `# Repo Health Report: ${analysis.repository.name}`,
      '',
      `- Repository: [${analysis.repository.ownerSlug}/${analysis.repository.slug}](${analysis.repository.webUrl})`,
      `- Health Score: **${score}/100 (${this.rating(score)})**`,
      `- Potential Score: **${analysis.potentialScore ?? score}/100**`,
      `- Data Coverage: **${analysis.dataCoverage ?? 0}%**`,
      `- Methodology: **${analysis.methodology}**`,
      `- Generated: **${new Date().toISOString()}**`,
      '',
      '## Category breakdown',
      '',
      '| Category | Score | Weight | Status | Summary |',
      '|---|---:|---:|---|---|',
      ...analysis.categories.map(
        (category) =>
          `| ${this.label(category.category)} | ${category.score ?? 'N/A'} | ${Math.round(category.weight * 100)}% | ${category.status} | ${this.escape(category.summary ?? '')} |`,
      ),
      '',
      '## Metrics',
      '',
      ...analysis.categories.flatMap((category) => [
        `### ${this.label(category.category)}`,
        '',
        ...(category.metrics.length
          ? category.metrics.map(
              (metric) =>
                `- **${this.label(metric.key)}:** ${metric.normalizedScore ?? 'N/A'}/100 - ${metric.explanation ?? ''}`,
            )
          : ['- No metric data available.']),
        '',
      ]),
      '## Recommendations',
      '',
      ...(analysis.recommendations.length
        ? analysis.recommendations.map(
            (recommendation, index) =>
              `${index + 1}. **[${recommendation.priority}] ${recommendation.title}** (+${recommendation.expectedScoreDelta ?? 0})\n   - Problem: ${recommendation.problem}\n   - Action: ${recommendation.action}`,
          )
        : ['No recommendations - all implemented checks passed.']),
      '',
      '---',
      'Generated by SourceCraft Repo Health. Scores reflect only the data coverage shown above.',
      '',
    ];
    return lines.join('\n');
  }

  async pdf(analysisId: string): Promise<Buffer> {
    const analysis = await this.analyses.findById(analysisId);
    return this.renderPdf(analysis);
  }

  renderPdf(analysis: ReportAnalysis): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margins: { top: 54, left: 54, right: 54, bottom: 64 }, bufferPages: true, info: { Title: `Repo Health Report - ${analysis.repository.name}`, Author: 'SourceCraft Repo Health' } });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('error', reject);
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.registerFont('Inter', require.resolve('dejavu-fonts-ttf/ttf/DejaVuSans.ttf'));
      doc.registerFont('Inter-Bold', require.resolve('dejavu-fonts-ttf/ttf/DejaVuSans-Bold.ttf'));
      doc.font('Inter');

      const score = analysis.score ?? 0;
      doc.rect(0, 0, doc.page.width, 190).fill('#101828');
      doc.fillColor('#84CAFF').font('Inter-Bold').fontSize(12).text('SOURCECRAFT REPO HEALTH', 54, 48);
      doc.fillColor('#FFFFFF').fontSize(25).text(analysis.repository.name, 54, 78, { width: 360 });
      doc.font('Inter').fontSize(10).fillColor('#D0D5DD').text(`${analysis.repository.ownerSlug}/${analysis.repository.slug}`, 54, 157);
      doc.roundedRect(430, 48, 110, 104, 12).fill(this.scoreColor(score));
      doc.fillColor('#FFFFFF').font('Inter-Bold').fontSize(34).text(String(score), 430, 68, { width: 110, align: 'center' });
      doc.fontSize(10).text(this.rating(score).toUpperCase(), 430, 112, { width: 110, align: 'center' });
      doc.y = 220;

      this.heading(doc, 'Overview');
      this.kpi(doc, 'Potential', `${analysis.potentialScore ?? score}/100`, 54);
      this.kpi(doc, 'Coverage', `${analysis.dataCoverage ?? 0}%`, 224);
      this.kpi(doc, 'Method', analysis.methodology, 394);
      doc.y = 310;

      this.heading(doc, 'Category breakdown');
      for (const category of analysis.categories) {
        this.ensureSpace(doc, 58);
        const y = doc.y;
        doc.roundedRect(54, y, 487, 46, 6).fill('#F2F4F7');
        doc.fillColor('#344054').font('Inter-Bold').fontSize(10).text(this.label(category.category), 68, y + 10, { width: 190 });
        doc.font('Inter').fontSize(8).fillColor('#667085').text(category.summary ?? category.status, 68, y + 26, { width: 330, ellipsis: true });
        doc.fillColor(this.scoreColor(category.score ?? 0)).font('Inter-Bold').fontSize(18).text(category.score === null ? 'N/A' : String(category.score), 450, y + 13, { width: 70, align: 'right' });
        doc.y = y + 56;
      }

      this.ensureSpace(doc, 90);
      this.heading(doc, 'Priority recommendations');
      const recommendations = analysis.recommendations.slice(0, 12);
      if (!recommendations.length) doc.font('Inter').fontSize(10).fillColor('#475467').text('No recommendations - all implemented checks passed.');
      for (const recommendation of recommendations) {
        this.ensureSpace(doc, 82);
        const y = doc.y;
        doc.fillColor('#F9FAFB').roundedRect(54, y, 487, 68, 6).fill();
        doc.fillColor('#175CD3').font('Inter-Bold').fontSize(8).text(recommendation.priority, 68, y + 10);
        doc.fillColor('#101828').fontSize(11).text(recommendation.title, 68, y + 25, { width: 350 });
        doc.font('Inter').fontSize(8).fillColor('#475467').text(recommendation.action, 68, y + 43, { width: 385, height: 20, ellipsis: true });
        doc.fillColor('#067647').font('Inter-Bold').fontSize(11).text(`+${recommendation.expectedScoreDelta ?? 0}`, 460, y + 25, { width: 60, align: 'right' });
        doc.y = y + 78;
      }

      const range = doc.bufferedPageRange();
      for (let page = 0; page < range.count; page += 1) {
        doc.switchToPage(page);
        doc.page.margins.bottom = 0;
        doc.font('Inter').fontSize(8).fillColor('#98A2B3').text(
          `Generated ${new Date().toISOString().slice(0, 10)}  |  Data coverage ${analysis.dataCoverage ?? 0}%  |  Page ${page + 1} of ${range.count}`,
          54,
          812,
          { width: 487, align: 'center', lineBreak: false },
        );
      }
      doc.end();
    });
  }

  private heading(doc: PDFKit.PDFDocument, text: string): void {
    doc.fillColor('#101828').font('Inter-Bold').fontSize(14).text(text, 54, doc.y, {
      width: 487,
    });
    doc.moveDown(0.7);
  }

  private kpi(doc: PDFKit.PDFDocument, label: string, value: string, x: number): void {
    doc.roundedRect(x, 252, 147, 48, 6).fill('#EFF8FF');
    doc.fillColor('#475467').font('Inter').fontSize(8).text(label, x + 12, 262);
    doc.fillColor('#175CD3').font('Inter-Bold').fontSize(13).text(value, x + 12, 277, { width: 123 });
  }

  private ensureSpace(doc: PDFKit.PDFDocument, height: number): void {
    if (doc.y + height > 755) doc.addPage();
  }

  private rating(score: number): string {
    if (score >= 90) return 'Excellent';
    if (score >= 75) return 'Good';
    if (score >= 50) return 'Attention';
    return 'Critical';
  }

  private scoreColor(score: number): string {
    if (score >= 90) return '#067647';
    if (score >= 75) return '#175CD3';
    if (score >= 50) return '#DC6803';
    return '#B42318';
  }

  private label(value: string): string {
    return value.toLowerCase().replaceAll('_', ' ').replace(/\b\w/g, (char) => char.toUpperCase());
  }

  private escape(value: string): string {
    return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
  }
}
